### ISSUE TITLE
Projects section on the site

### ISSUE THREAD

**Issue by articobandurini** [leapdao/leapdao-website#102]
# Bounty

## Scope
We have a few ecosystem projects and they need to be listed on the website.

## Deliverables
A PR with the projects section (logo, title, short description, link) added to the site.
- planet a
- dungeon riches
- project.democracy
- motion protocol

## Gain for the project
Ecosystem visibility, showcase, attracting new eco devs.

### Publicly visible delivery
Section on the site

## Roles
bounty gardener: @articobandurini / 10%
bounty worker: @articobandurini / 75%
bounty reviewer: name  / 15%

**Comment by troggy** [comment]
how is it going?

**Comment by articobandurini** [comment]
@troggy up for review?
