### ISSUE TITLE
add RSS feed to blog

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leapdao-website#139]
# Bounty

currently the blog does not expose an RSS feed. hence it is not possible to subscribe to posts or use other readers. 

without RSS podcasting is also not possible using the blog.

## Scope

- enable the generation of an RSS during build of the website
- include all blog articles in the RSS feed
- (optional) if the blog contains a media file, include in RSS feed

## Deliverables

- create `rss.xml.js` in `/blog`
- test subscription with Feedly, or some other mobile feed reader

## Gain for the project

- more reach through subscriptions
- ability to start podcast

### Publicly visible delivery

rss feed

## Roles
bounty gardener: @johannbarbie  / 10%
bounty worker: @sunify  / 70%
bounty reviewer: name / share

**Comment by troggy** [comment]
@johannbarbie so how to use it?

**Comment by troggy** [comment]
there is no link to RSS anywhere, autodiscovery is not working and https://leapdao.org/blog/rss.xml shows 500 😢

**Comment by sunify** [comment]
Build failed 👀

**Comment by sunify** [comment]
It works now https://leapdao.org/rss.xml
