### ISSUE TITLE
Ventures Page - Content

### ISSUE THREAD

**Issue by Clearwood** [leapdao/leapdao-website#163]
# Bounty
For Businesses to choose us they need to know how we can help them succeed. 

## Scope

- new page focussing on business customers
- pitch leapdao skills and list crews and refences
- CTA: subscribe to newsletter + request a demo (post into slack)

## Deliverables

- text
- page mockup

## Roles
bounty gardener: @Clearwood  / 50 DAI 
bounty worker: @zschavi @johannbarbie  / half-half
bounty reviewer: @Clearwood  / 15%

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform

**Comment by zschavi** [comment]
need to catch up on this one, sry for delay

**Comment by Clearwood** [comment]
@zschavi any updates?

**Comment by johannbarbie** [comment]
code was too much, forked out into extra bounty: https://github.com/leapdao/leapdao-website/issues/179

**Comment by johannbarbie** [comment]
ready for review: https://docs.google.com/drawings/d/1Qu5Kz7ox-PH07jazK0G8tisEUld2o9M2ReyLA-YyFZ4

**Comment by Clearwood** [comment]
would all ventures be listed?
This looks great :+1: 
I am just wondering a bit whether the why should be as idealistic. threatens the freedom of individuals and the survival of democracy is a pretty big statement IMO.

**Comment by zschavi** [comment]
@Clearwood - thanks for feedback!

we displayed some examples like status, nervos & wr, cubes or icons could rotate or switch similar to carousel :)
could be divided by recent & past projects. do you have more ideas?

about the idealistic tone:
we identified a target group & people we want to address with the page.
Think about developers & visionaries for Web3/DApp concepts & development. Another group is crypto startups, and so on...
We had some specific hopes/fears/pains/gains in mind when adressing these readers:
* quick time to market
* avoid high gas cost
* convenient onboarding for end-users
* build a strong partnership, trust
Hope we created a positive message.

**Comment by Clearwood** [comment]
I think the carousel is a great idea, really good work. 
I really like the content, I just had an uneasy feeling about this sentence: `The centralization of the web into the hands of a few tech giants threatens the freedom of individuals and the survival of democracy. ` Not because I don't believe for it to be true but I was rather asking myself whether we need to tell those people about the problem again, rather than just talking about our vision.

**Comment by zschavi** [comment]
The sentence in question opens up our "Why?" quite fitting, or is the painted picture too dark ?

Let's close the issue and work on the forked one to get it online :)

**Comment by Clearwood** [comment]
> The sentence in question opens up our "Why?" quite fitting, or is the painted picture too dark ?
> 
> Let's close the issue and work on the forked one to get it online :)

I feel like it is expected. Every decentralized project will tell you this and it's a pretty dark picture.

**Comment by johannbarbie** [comment]
`The centralization of the web into the hands of a few tech giants threatens the freedom of individuals and the survival of democracy. LeapDAO seeks to sustainably decentralize power by enabling web-citizens to own their data and communities to govern themselves and flourish in the process.`

i agree, this should be formulated more positive. @zschavi  @Clearwood  is this better?

`Decentralization is a vital ingredient to open and wide-scale networks like the internet and global cosmopolitanism. Centralization of power can subvert such networks and hinder the evolution of the human species. LeapDAO seeks to sustainably decentralize power by enabling web-citizens to own their data and communities to govern themselves and flourish in the process.`

**Comment by Clearwood** [comment]
@johannbarbie yes this is what I had in mind :rocket:
