### ISSUE TITLE
Redesign Blog Page

### ISSUE THREAD

**Issue by Clearwood** [leapdao/leapdao-website#164]
# Bounty
Let's be proud of our work and feature our blog better.

## Scope

- visible first paragraph / description
- tags for blogpost
- some blog posts should be recommended
- some kind of sort possibility

## Deliverables

- updated code

## Roles
bounty gardener: @Clearwood  / 50 DAI 
bounty worker: @mwaa  / 250 DAI
bounty reviewer: name / 50 DAI

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [ ] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by Clearwood** [comment]
@mwaa do you have any updates on your work?

**Comment by mwaa** [comment]
@Clearwood got  draft PR. Looking to submit rest of changes during the day
