### ISSUE TITLE
Venture Onboarding Pipeline

### ISSUE THREAD

**Issue by mwaa** [leapdao/leapdao-website#186]
# Bounty
Call To Actions (Demo & Schedule Call)  on ventures page need data collection forms
Collected data in forms are posted on Slack and Email sent to a leapdao biz email or vice versa

## Scope

- Two google forms one for demo and second for calls (Alternatives are welcomed)
- Add links to ventures page once the forms are available
- Information collected needs to trigger email or posted to slack channel. Might need to run Task on AWS
- Bare minimum information collected contact info, main topic of discussion and any more context message
- Create a private group on slack with all biz dev roles to act on data posted in channel
- Also follow up task what possible demos can be created

## Deliverables

- New Slack Channel
- Forms and Trigger task to Slack/Email

## Roles
bounty gardener: @mwaa / 40 DAI 
bounty worker:  @mwaa / 120 DAI
bounty reviewer: name / 40 DAI

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [x] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by Clearwood** [comment]
https://github.com/leapdao/leapdao-website/issues/179#issuecomment-677662605

**Comment by mwaa** [comment]
Deliverables

1. New slack channel `#biz-dev`
2. Contact Request form has been added using [commit](https://github.com/leapdao/leapdao-website/pull/185/commits/e75a28f7dd7260f8e9b3afa69e7cc1eac64d2612)
3. New Trello board also linked to slack channel. Biz devs can join the slack channel then join the board and subscribe to its tasks

Form+Trello Board
- https://shrtco.de/leap-contact-request
- https://trello.com/b/4IHtjS4s/partnership-onboarding

_No clear way to automate tasks from google form hence biz devs have to create trello cards using the slack commands_

Proof of Actions as on Slack Channel
![2020-09-15-13-29-app slack com](https://user-images.githubusercontent.com/5112468/93201527-fc951480-f759-11ea-901e-e08d4889cdd9.png)
![2020-09-15-13-27-trello com](https://user-images.githubusercontent.com/5112468/93201536-fef76e80-f759-11ea-9eb2-0ba9012bde3c.png)
