### ISSUE TITLE
Blog Post | Announcing Ethereum Foundation Grant 

### ISSUE THREAD

**Issue by kohola71** [leapdao/leapdao-website#32]
**Scope:** 
We want to announce that LeapDAO received the 2nd Ethereum Grant and reference the EF blog post https://blog.ethereum.org/2019/02/21/ethereum-foundation-grants-program-wave-5/ We want to also explain what's next in the pipeline and what the funds will be used for. We will invite developers to get involved by solving bounties. 

**Deliverables:** 
Blog post copy 
Tweets 

**Gains for project:** 
New Developers / Community outreach 
PR/Marketing 

**Roles:**
bounty gardener: kohola / 10% 
bounty worker: kohola / 70% 
bounty reviewer: johba / 20%

**Comment by johannbarbie** [comment]
completed by https://github.com/leapdao/leapdao-website/pull/34
