### ISSUE TITLE
"How we work" page on our website

### ISSUE THREAD

**Issue by articobandurini** [leapdao/leapdao-website#62]
# Bounty

## Scope

Create "How we work" page on our website, describing our working process in details: team, holocracy, meetings, reputation, etc. It should provide a clear vision of how our work is organised and therefore engage developers to join our community.

### Some useful thoughts 
Why:
- We're providing infrastructure and blueprints for how "crypto startups" should be run => DAOs/Guilds
- We're enabling a new way to work for creative workers that I bet will outperform classical employment in the future: https://twitter.com/TimDaub/status/1137501322855497728
- We're shipping actual working code
- We're living https://en.wikipedia.org/wiki/Conway%27s_law
- Investors will find this interesting!
- Not many people know about the inner workings of LeapDAO yet, so let's spread this information!
 - To get more hands on board
 - To spread the vision

What the blog post should cover:
- What the project does
- Holocracy
- Circles and how budgets are handled
- bounties
- a few numbers. e.g. show treasury. Lots of people will be shocked!
- opinions of contributors?
- etc.

## Deliverables

Pull request with a page called "how-we-work.html" linked from the landing page.

## Gain for the project

Encouraging developers to join our community and speed up development process.

### Publicly visible delivery

Page on the website available for all new developers.

## Roles
bounty gardener: @articobandurini / 15%
bounty worker: @articobandurini / 70%
bounty reviewer: name / 15%

**Comment by johannbarbie** [comment]
timed out
