### ISSUE TITLE
Create "Apply for a Grant" form

### ISSUE THREAD

**Issue by articobandurini** [leapdao/leapdao-website#92]
# Bounty

## Scope

- Ecosystem circle wants to bring mass adoption closer and therefore announces grants for enterpreneurs and teams which develop dApps using Leap plasma network.
- In order to apply for such a grant one must submit a form with several questions answered about them and the dApp they're going to build.
- Link to the form has to be published on the Earn page (and social media as well).

## Deliverables

Google form with a set of questions, saving answers and sending them to email.

## Gain for the project

Mass adoption one step closer.

### Publicly visible delivery

Google form with a set of questions, linked to the Earn page.

## Roles
bounty gardener: @articobandurini  / 15%
bounty worker: @articobandurini  / 70%
bounty reviewer: @TimDaub / 15%

**Comment by articobandurini** [comment]
The form is here: https://docs.google.com/forms/d/e/1FAIpQLSeN9N96hkwyuKSR_QF7O_CSfG7gUQ_rA57y9DZjIk7XZEybyg/viewform

**Comment by johannbarbie** [comment]
<img width="520" alt="Screen Shot 2019-07-29 at 5 08 39 PM" src="https://user-images.githubusercontent.com/659301/62059570-d9409a80-b223-11e9-9292-428461b6ea1b.png">

why not have this post into slack?

**Comment by johannbarbie** [comment]
the form has typos:
`How many people is in the team?`
should be
`How many people are in the team?` or even better english: `How big is the team?`

**Comment by johannbarbie** [comment]
also, why is the form yellow?

**Comment by articobandurini** [comment]
all suggestions by @johannbarbie are implemented, closing the issue
